cms_homepage:
    path:     /
    defaults: { _controller: DyweeCMSBundle:Page:index }

page_list:
    path:     /cms/list
    defaults: { _controller: DyweeCMSBundle:Page:list }

page_table:
    path:     /admin6833/cms/table
    defaults: { _controller: DyweeCMSBundle:Page:table }

page_view:
    path:     /page/{data}
    defaults: { _controller: DyweeCMSBundle:Page:view }

page_view_content:
    path:     /page/{data}/onlyContent
    defaults: { _controller: DyweeCMSBundle:Page:viewContent }

page_add:
    path:     /admin6833/cms/add
    defaults: { _controller: DyweeCMSBundle:Page:add }

page_update:
    path:     /admin6833/page/update/{id}
    defaults: { _controller: DyweeCMSBundle:Page:update }
    requirements:
        id: \d+

page_details:
    path:     /admin6833/page/{id}/details
    defaults: { _controller: DyweeCMSBundle:PageAdmin:view }
    requirements:
        id: \d+

page_delete:
    path:     /admin6833/page/delete/{id}
    defaults: { _controller: DyweeCMSBundle:Page:delete }
    requirements:
        id: \d+

cms_view_contact_page:
    path:     /page/contact
    defaults: { _controller: DyweeCMSBundle:Page:viewContact }

cms_inMenu_switch:
    path:     /admin6833/page/{id}/inMenuSwitch
    defaults: { _controller: DyweeCMSBundle:Page:inMenuSwitch }
    requirements:
        id: \d+

cms_getPageElementDashboard_byAjax:
    path:     /admin6833/cms/pageElement/ajaxDashboard
    defaults: { _controller: DyweeCMSBundle:PageElement:ajaxDashboard, _locale: 'fr'}
    options:
        expose: true

cms_install:
    path:     /cms/install
    defaults: {_controller: DyweeCMSBundle:Core:install}

notification_add:
    path:     /cms/notification/add
    defaults: { _controller: DyweeCMSBundle:Notification:add }

notification_update:
    path:     /cms/notification/{id}/update
    defaults: { _controller: DyweeCMSBundle:Notification:update }

notification_table:
    path:     /cms/notification/table
    defaults: { _controller: DyweeCMSBundle:Notification:table}

notification_delete:
    path:     /cms/notification/{id}/delete
    defaults: { _controller: DyweeCMSBundle:Notification:remove }