cms_homepage:
    path:     /
    defaults: { _controller: DyweeCMSBundle:Page:index }

page_list:
    path:     /cms/list
    defaults: { _controller: DyweeCMSBundle:Page:list }

page_table:
    path:     /admin/cms/table
    defaults: { _controller: DyweeCMSBundle:Page:table }

page_view:
    path:     /page/{data}
    defaults: { _controller: DyweeCMSBundle:Page:view }

cms_view:
    path:     /page/{data}
    defaults: { _controller: DyweeCMSBundle:Page:view }

page_view_content:
    path:     /page/{data}/onlyContent
    defaults: { _controller: DyweeCMSBundle:Page:viewContent }

page_add:
    path:     /admin/cms/add
    defaults: { _controller: DyweeCMSBundle:Page:add }

page_update:
    path:     /admin/page/update/{id}
    defaults: { _controller: DyweeCMSBundle:Page:update }
    requirements:
        id: \d+

page_details:
    path:     /admin/page/{id}/details
    defaults: { _controller: DyweeCMSBundle:PageAdmin:view }
    requirements:
        id: \d+

page_delete:
    path:     /admin/page/delete/{id}
    defaults: { _controller: DyweeCMSBundle:Page:delete }
    requirements:
        id: \d+

cms_view_contact_page:
    path:     /page/contact
    defaults: { _controller: DyweeCMSBundle:Page:viewContact }

page_inMenu_switch:
    path:     /admin/page/{id}/inMenuSwitch
    defaults: { _controller: DyweeCMSBundle:Page:inMenuSwitch }
    requirements:
        id: \d+

cms_getPageElementDashboard_byAjax:
    path:     /admin/cms/pageElement/ajaxDashboard
    defaults: { _controller: DyweeCMSBundle:PageElement:ajaxDashboard, _locale: 'fr'}
    options:
        expose: true

cms_install:
    path:     /cms/install
    defaults: {_controller: DyweeCMSBundle:Core:install}


#####################################
#                                   #
#     ROUTING DES FORMULAIRES       #
#                                   #
#####################################


cms_customForm_table:
    path:     /admin6833/modules/customForm/table
    defaults: { _controller: DyweeCMSBundle:DyweeForm:table }

cms_customForm_add:
    path:     /admin6833/modules/customForm/add
    defaults: { _controller: DyweeCMSBundle:DyweeForm:add}
    options:
        expose: true

cms_customForm_update:
    path:     /admin6833/modules/customForm/{id}/update
    defaults: { _controller: DyweeCMSBundle:DyweeForm:update }
    requirements:
        id: \d+

cms_customForm_delete:
    path:     /admin6833/modules/customForm/{id}/delete
    defaults: { _controller: DyweeCMSBundle:DyweeForm:delete }
    requirements:
        id: \d+

cms_customForm_preview:
    path:     /admin6833/modules/customForm/{id}/preview
    defaults: { _controller: DyweeCMSBundle:DyweeForm:preview }
    requirements:
        id: \d+

cms_customForm_display:
    path:     /admin6833/modules/customForm/{id}/display
    defaults: { _controller: DyweeCMSBundle:DyweeForm:displayForm }
    requirements:
        id: \d+

cms_customFormResponse_table:
    path:     /admin6833/modules/customFormResponse/{formId}/table
    defaults: { _controller: DyweeCMSBundle:FormResponse:table }
    requirements:
        formId: \d+

cms_customFormResponse_view:
    path:     /admin6833/modules/customFormResponse/{id}/view
    defaults: { _controller: DyweeCMSBundle:FormResponse:myView }
    requirements:
        id: \d+

cms_customFormResponse_delete:
    path:     /admin6833/modules/customFormResponse/{id}/delete
    defaults: { _controller: DyweeCMSBundle:FormResponse:delete }
    requirements:
        id: \d+

cms_customForm_json:
    path:   /admin6833/customForm/json
    defaults: { _controller: DyweeCMSBundle:DyweeForm:json}
    options:
        expose: true