page_list:
    path:     /cms/list
    defaults: { _controller: DyweeCMSBundle:Page:list }

page_view_content:
    path:     /page/{data}/onlyContent
    defaults: { _controller: DyweeCMSBundle:Page:viewContent }

page_details:
    path:     /admin/page/{id}/details
    defaults: { _controller: DyweeCMSBundle:PageAdmin:view }
    requirements:
        id: \d+

cms_view_contact_page:
    path:     /page/contact
    defaults: { _controller: DyweeCMSBundle:Page:viewContact }

page_inMenu_switch:
    path:     /admin/page/{id}/inMenuSwitch
    defaults: { _controller: DyweeCMSBundle:Page:inMenuSwitch }
    requirements:
        id: \d+

cms_getPageElementDashboard_byAjax:
    path:     /admin/cms/pageElement/ajaxDashboard
    defaults: { _controller: DyweeCMSBundle:PageElement:ajaxDashboard, _locale: 'fr'}
    options:
        expose: true

cms_install:
    path:     /cms/install
    defaults: {_controller: DyweeCMSBundle:Core:install}


#####################################
#                                   #
#     ROUTING DES FORMULAIRES       #
#                                   #
#####################################


cms_customFormResponse_table:
    path:     /admin6833/modules/customFormResponse/{formId}/table
    defaults: { _controller: DyweeCMSBundle:FormResponse:table }
    requirements:
        formId: \d+

cms_customFormResponse_view:
    path:     /admin6833/modules/customFormResponse/{id}/view
    defaults: { _controller: DyweeCMSBundle:FormResponse:myView }
    requirements:
        id: \d+

cms_customFormResponse_delete:
    path:     /admin6833/modules/customFormResponse/{id}/delete
    defaults: { _controller: DyweeCMSBundle:FormResponse:delete }
    requirements:
        id: \d+