page_details:
    path:     /admin/page/{id}/details
    defaults: { _controller: DyweeCMSBundle:PageAdmin:view }
    requirements:
        id: \d+

cms_getPageElementDashboard_byAjax:
    path:     /admin/cms/pageElement/ajaxDashboard
    defaults: { _controller: DyweeCMSBundle:PageElement:ajaxDashboard, _locale: 'fr'}
    options:
        expose: true

cms_install:
    path:     /cms/install
    defaults: {_controller: DyweeCMSBundle:Core:install}