services:
    dywee_cms.sidebar_handler:
        class: Dywee\CMSBundle\Service\CMSAdminSidebarHandler
        arguments: [ '@router' ]

    dywee_cms.admin_sidebar_listener:
        class: Dywee\CMSBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_cms.sidebar_handler' ]
        tags:
            - { name: kernel.event_subscriber }