services:
    dywee_cms.sidebar_handler:
        class: Dywee\CMSBundle\Service\CMSAdminSidebarHandler
        arguments: [ '@router' ]

    dywee_cms.admin_sidebar_listener:
        class: Dywee\CMSBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_cms.sidebar_handler' ]
        tags:
            - { name: kernel.event_subscriber }


    ######   PLUGINS BOX  #########

    dywee_cms.plugin_box_handler:
        class: Dywee\CMSBundle\Service\PageElementModalHandler
        arguments: [  ]

    dywee_cms.plugin_box_listener:
        class: Dywee\CMSBundle\Listener\PageElementModalListener
        arguments: [ '@dywee_cms.plugin_box_handler' ]
        tags:
            - { name: kernel.event_subscriber }