services:
    ###########################
    #                         #
    #         SIDEBAR         #
    #                         #
    ###########################

    dywee_cms.admin_sidebar_listener:
        class: Dywee\CMSBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_cms.sidebar_handler' ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_cms.sidebar_handler:
        class: Dywee\CMSBundle\Service\AdminSidebarHandler
        arguments: [ '@router' ]

    ###########################
    #                         #
    #        DASHBOARD        #
    #                         #
    ###########################

    dywee_cms.admin_dashboard_listener:
        class: Dywee\CMSBundle\Listener\AdminDashboardBuilderListener
        arguments: [ '@dywee_cms.dashboard_handler' ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_cms.dashboard_handler:
        class: Dywee\CMSBundle\Service\AdminDashboardHandler
        arguments: [ '@router' ]
        
    ###########################
    #                         #
    #        PAGE ADMIN       #
    #                         #
    ###########################

    dywee_cms.plugin_box_handler:
        class: Dywee\CMSBundle\Service\PageElementModalHandler

    dywee_cms.plugin_box_listener:
        class: Dywee\CMSBundle\Listener\PageElementModalListener
        arguments: [ '@dywee_cms.plugin_box_handler' ]
        tags:
            - { name: kernel.event_subscriber }


    ###########################
    #                         #
    #          PLUGIN         #
    #                         #
    ###########################

    dywee_cms.custom_form_builder:
        class: Dywee\CMSBundle\Service\CustomFormBuilder
        arguments:
            - '@form.factory'