<?php

namespace Dywee\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\Date;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageStatRepository extends EntityRepository
{
    public function findLastStatsForPage($page, $detail = 'daily'){
        $qb = $this->createQueryBuilder('s')
            ->select('count(s.id) as total, s.createdAt, DATE(s.createdAt) as dateOnly')
            ->where('s.page = :page')
            ->setParameters(array('page' => $page['id']))
            ->orderBy('s.createdAt', 'asc')
            ->setMaxResults(6);

        if($detail == 'daily')
            $qb->groupBy('dateOnly');

        return $qb->getQuery()->getResult();
    }
}
