<?php

namespace Dywee\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageTextElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTextElementRepository extends EntityRepository
{
}
