<?php

namespace Dywee\CMSBundle\Repository;

use Dywee\CMSBundle\Entity\Page;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
    class PageRepository extends NestedTreeRepository
{
    public function getForParent()
    {
        $queryBuilder = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.inMenu = 1')
        ;

        return $queryBuilder;
    }

    public function findHomePage()
    {
        $queryBuilder = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.type = :type')
            ->setParameter('type', Page::TYPE_HOMEPAGE);

        $query = $queryBuilder->getQuery();

        /*$query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );*/

        return $query->getSingleResult();
    }

    public function getMenu()
    {
        $queryBuilder = $this->createQueryBuilder('p')
            ->select('p')
            ->leftJoin('DyweeCMSBundle:Page', 'pc', 'with', 'pc.parent = p.id')
            ->where('p.inMenu = 1 and p.parent is null')
            ->orderBy('p.menuOrder', 'asc');

        $query = $queryBuilder->getQuery();

        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );

        return $query->getResult();
    }

    public function countPage($state = null)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('count(p)')
            ;

        if($state)
            $qb->andWhere('p.state = :state')->setParameter('state', $state);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
