<?php

namespace Dywee\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageElementRepository extends EntityRepository
{
}
